// src/components/layout/Header.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { IconMenu2, IconX } from "@tabler/icons-react";
import { AnimatePresence, motion } from "framer-motion";
import { SOCIALS } from "./socials";

const NAV_LINKS = [
  { label: "Gallery", href: "/gallery" },
  { label: "Experience", href: "/experience" },
  { label: "Pricing", href: "/pricing" },
  { label: "Availability", href: "/availability" },
  { label: "FAQs", href: "/faqs" },
  { label: "About", href: "/about" },
  { label: "Other Venues", href: "/locations" },
];

export default function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const pathname = usePathname();
  const isHome = pathname === "/";
  const transparent = isHome && !scrolled && !menuOpen;

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll, { passive: true });
    onScroll();
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  // Lock body scroll while the menu is open; close on Escape.
  useEffect(() => {
    if (!menuOpen) return;
    document.body.style.overflow = "hidden";
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") setMenuOpen(false);
    };
    window.addEventListener("keydown", onKeyDown);
    return () => {
      document.body.style.overflow = "";
      window.removeEventListener("keydown", onKeyDown);
    };
  }, [menuOpen]);

  return (
    <>
      <header
        className={`fixed top-0 inset-x-0 z-50 transition-colors duration-300 ${
          transparent ? "bg-transparent border-b border-transparent" : "bg-canvas border-b border-rule"
        }`}
      >
        <div className="flex items-center justify-between px-6 md:px-10 h-[60px] pad-12">
          {/* Wordmark */}
          <Link href="/" className="flex-shrink-0">
            <div
              className={`font-display text-[26px] tracking-[0.12em] uppercase leading-none transition-colors duration-300 ${
                transparent ? "text-white" : "text-ink"
              }`}
            >
              The Haven
            </div>
          </Link>

          {/* Socials + CTA + menu trigger */}
          <div className="flex items-center gap-4 md:gap-6">
            <div className="hidden md:flex items-center gap-4">
              {SOCIALS.map(({ icon: Icon, href, label }) => (
                <a
                  key={href}
                  href={href}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={label}
                  className={`transition-colors duration-300 ${
                    transparent ? "text-white/70 hover:text-white" : "text-ink-mid hover:text-ink"
                  }`}
                >
                  <Icon size={16} />
                </a>
              ))}
            </div>
            <Link
              href="https://calendly.com/thehaveneventspace"
              target="_blank"
              rel="noopener noreferrer"
              className={`hidden sm:inline-flex items-center font-body text-[10px] font-medium tracking-[0.2em] uppercase px-5 py-[10px] transition-colors duration-300 ${
                transparent ? "bg-white text-ink hover:bg-rule" : "bg-ink text-canvas hover:bg-ink-faint"
              }`}
            >
              Schedule a Tour
            </Link>
            {/* Spacer preserving the menu trigger's layout width; the real button
                renders below as its own fixed element so it stacks above the
                full-page overlay, which sits above the header. */}
            <span className="invisible flex items-center gap-3 p-1" aria-hidden="true">
              <span className="font-body text-[10px] font-medium tracking-[0.22em] uppercase">Menu</span>
              <IconMenu2 size={22} />
            </span>
          </div>
        </div>
      </header>

      {/* Menu trigger: fixed independently of header/overlay so it always
          renders above the full-page overlay (a sibling fixed element can't
          be out-z-indexed from inside the header's own stacking context). */}
      <div className="fixed top-0 right-0 z-[60] h-24 flex items-center pr-6 md:pr-10">
        <button
          className={`flex items-center gap-3 p-1 transition-colors duration-300 ${
            transparent ? "text-white" : "text-ink"
          }`}
          onClick={() => setMenuOpen((open) => !open)}
          aria-label={menuOpen ? "Close menu" : "Open menu"}
          aria-expanded={menuOpen}
        >
          <span className="font-body text-[10px] font-medium tracking-[0.22em] uppercase">
            {menuOpen ? "Close" : "Menu"}
          </span>
          {menuOpen ? <IconX size={22} /> : <IconMenu2 size={22} />}
        </button>
      </div>

      {/* Full-screen overlay menu */}
      <AnimatePresence>
        {menuOpen && (
          <motion.div
            className="fixed inset-0 z-[55] flex flex-col bg-canvas"
            initial={{ y: "-100%" }}
            animate={{ y: 0 }}
            exit={{ y: "-100%" }}
            transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
          >
            <nav className="flex flex-col px-6 pt-28 pb-12 gap-8">
              {NAV_LINKS.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  onClick={() => setMenuOpen(false)}
                  className="font-display text-[36px] tracking-[0.06em] uppercase hover:text-ink-low transition-colors transparent"
                >
                  {link.label}
                </Link>
              ))}
            </nav>
            <div className="px-6 pb-10 mt-auto">
              <Link
                href="https://calendly.com/thehaveneventspace"
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => setMenuOpen(false)}
                className="inline-flex items-center font-body text-[10px] font-medium tracking-[0.2em] uppercase text-ink px-6 py-3 transparent"
              >
                Schedule a Tour
              </Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

// app/components/layout/Header.vue
<script setup lang="ts">
import { IconMenu2, IconX } from "@tabler/icons-vue";

const NAV_LINKS = [
  { label: "Gallery", href: "/gallery" },
  { label: "Experience", href: "/experience" },
  { label: "Pricing", href: "/pricing" },
  { label: "Availability", href: "/availability" },
  { label: "FAQs", href: "/faqs" },
  { label: "About", href: "/about" },
  { label: "Other Venues", href: "/locations" },
];
const TOUR_URL = "https://calendly.com/thehaveneventspace";

const route = useRoute();
const menuOpen = ref(false);
const scrolled = ref(false);

// Transparent only over the home hero, before scrolling, with the menu closed.
const transparent = computed(
  () => route.path === "/" && !scrolled.value && !menuOpen.value,
);

function onScroll() {
  scrolled.value = window.scrollY > 20;
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === "Escape") menuOpen.value = false;
}

onMounted(() => {
  window.addEventListener("scroll", onScroll, { passive: true });
  onScroll();
});

onBeforeUnmount(() => {
  window.removeEventListener("scroll", onScroll);
  window.removeEventListener("keydown", onKeyDown);
  document.body.style.overflow = "";
});

// Lock body scroll while the menu is open; close on Escape.
watch(menuOpen, (open) => {
  document.body.style.overflow = open ? "hidden" : "";
  if (open) window.addEventListener("keydown", onKeyDown);
  else window.removeEventListener("keydown", onKeyDown);
});
</script>

<template>
  <header class="header" :class="{ 'is-transparent': transparent }">
    <div class="header__inner">
      <NuxtLink to="/" class="header__wordmark">The Haven</NuxtLink>

      <div class="header__actions">
        <div class="header__socials">
          <a
            v-for="s in SOCIALS"
            :key="s.href"
            :href="s.href"
            target="_blank"
            rel="noopener noreferrer"
            :aria-label="s.label"
            class="header__social"
          >
            <component :is="s.icon" :size="16" />
          </a>
        </div>
        <a
          :href="TOUR_URL"
          target="_blank"
          rel="noopener noreferrer"
          class="header__cta"
        >
          Schedule a Tour
        </a>
        <!-- Spacer preserving the menu trigger's layout width; the real button
             is its own fixed element so it stacks above the full-page overlay. -->
        <span class="menu-btn menu-btn--spacer" aria-hidden="true">
          <span class="menu-btn__label">Menu</span>
          <IconMenu2 :size="22" />
        </span>
      </div>
    </div>
  </header>

  <div class="menu-trigger" :class="{ 'is-transparent': transparent }">
    <button
      class="menu-btn"
      :aria-label="menuOpen ? 'Close menu' : 'Open menu'"
      :aria-expanded="menuOpen"
      @click="menuOpen = !menuOpen"
    >
      <span class="menu-btn__label">{{ menuOpen ? "Close" : "Menu" }}</span>
      <IconX v-if="menuOpen" :size="22" />
      <IconMenu2 v-else :size="22" />
    </button>
  </div>

  <Transition name="slide-down">
    <div v-if="menuOpen" class="overlay">
      <nav class="overlay__nav">
        <NuxtLink
          v-for="link in NAV_LINKS"
          :key="link.href"
          :to="link.href"
          class="overlay__link"
          @click="menuOpen = false"
        >
          {{ link.label }}
        </NuxtLink>
      </nav>
      <div class="overlay__footer">
        <a
          :href="TOUR_URL"
          target="_blank"
          rel="noopener noreferrer"
          class="overlay__cta"
          @click="menuOpen = false"
        >
          Schedule a Tour
        </a>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.header {
  position: fixed;
  inset: 0 0 auto 0;
  z-index: 50;
  background: var(--color-canvas);
  border-bottom: 1px solid var(--color-rule);
  transition: background-color 0.3s, border-color 0.3s;
}
.header.is-transparent {
  background: transparent;
  border-bottom-color: transparent;
}

/* Same height as the menu trigger, same side padding as .container */
.header__inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 6rem;
  padding-inline: 1.5rem;
}

.header__wordmark {
  flex-shrink: 0;
  font-family: var(--font-display);
  font-size: 26px;
  line-height: 1;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--color-ink);
  transition: color 0.3s;
}
.is-transparent .header__wordmark {
  color: #fff;
}

.header__actions {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.header__socials {
  display: none;
  align-items: center;
  gap: 1rem;
}

.header__social {
  color: var(--color-ink-mid);
  transition: color 0.3s;
}
.header__social:hover {
  color: var(--color-ink);
}
.is-transparent .header__social {
  color: rgb(255 255 255 / 0.7);
}
.is-transparent .header__social:hover {
  color: #fff;
}

.header__cta {
  display: none;
  align-items: center;
  padding: 10px 1.25rem;
  font-size: 10px;
  font-weight: 500;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--color-canvas);
  background: var(--color-ink);
  transition: background-color 0.3s, color 0.3s;
}
.header__cta:hover {
  background: var(--color-ink-faint);
}
.is-transparent .header__cta {
  color: var(--color-ink);
  background: #fff;
}
.is-transparent .header__cta:hover {
  background: var(--color-rule);
}

/* Menu trigger */
.menu-trigger {
  position: fixed;
  top: 0;
  right: 0;
  z-index: 60;
  display: flex;
  align-items: center;
  height: 6rem;
  padding-right: 1.5rem;
  color: var(--color-ink);
  transition: color 0.3s;
}
.menu-trigger.is-transparent {
  color: #fff;
}

.menu-btn {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.25rem;
}
.menu-btn--spacer {
  visibility: hidden;
}
.menu-btn__label {
  font-size: 10px;
  font-weight: 500;
  letter-spacing: 0.22em;
  text-transform: uppercase;
}

/* Full-screen overlay */
.overlay {
  position: fixed;
  inset: 0;
  z-index: 55;
  display: flex;
  flex-direction: column;
  background: var(--color-canvas);
}
.overlay__nav {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  padding: 7rem 1.5rem 3rem;
}
.overlay__link {
  font-family: var(--font-display);
  font-size: 36px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  transition: color 0.15s;
}
.overlay__link:hover {
  color: var(--color-ink-low);
}
.overlay__footer {
  margin-top: auto;
  padding: 0 1.5rem 2.5rem;
}
.overlay__cta {
  display: inline-flex;
  align-items: center;
  padding: 0.75rem 1.5rem;
  font-size: 10px;
  font-weight: 500;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--color-ink);
}

.slide-down-enter-active,
.slide-down-leave-active {
  transition: transform 0.6s cubic-bezier(0.22, 1, 0.36, 1);
}
.slide-down-enter-from,
.slide-down-leave-to {
  transform: translateY(-100%);
}

@media (min-width: 640px) {
  .header__cta {
    display: inline-flex;
  }
}

@media (min-width: 768px) {
  .header__inner {
    padding-inline: 2.5rem;
  }
  .header__actions {
    gap: 1.5rem;
  }
  .header__socials {
    display: flex;
  }
  .menu-trigger {
    padding-right: 2.5rem;
  }
}
</style>
